name: build
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: build sdk docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Login Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Login GHCR
      uses: docker/login-action@v2
      with:
        registry: hub.qucheng.com
        username: ${{ secrets.TCR_USER }}
        password: ${{ secrets.TCR_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: | 
          easysoft/debian
          easysoft/debian:11
          easysoft/debian:11-r0
          hub.qucheng.com/library/debian
          hub.qucheng.com/library/debian:11
          hub.qucheng.com/library/debian:11-r0
