name: PRAutoMerge

on: pull_request

permissions: write-all

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull Request Automerge
        if: github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot]'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
